name: AOV Discord Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "*/10 * * * *"

jobs:
  aov-news:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Bot
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          python bot.py